### PR TITLE
update JVM-Protocol.md Skywalking-Cross-Process-Propagation-Headers-Protocol-v1.md Skywalking-Cross-Process-Propagation-Headers-Protocol-v2.md

### PR DESCRIPTION
**Pull request by SataQiu**
`docs/zh/master/protocols` 文件夹更新完毕！

请问我现在能申请加入咱们的 GitHub SkyAPM 组织吗？您能邀请下我吗？@kezhenxu94

### CODE REVIEW

**Comment by kezhenxu94** [comment]
> `docs/zh/master/protocols` 文件夹更新完毕！
> 
> 请问我现在能申请加入咱们的 GitHub SkyAPM 组织吗？您能邀请下我吗？@kezhenxu94

Hi @SataQiu , I have no privilege to invite you as a member of this organization, cc @wu-sheng

**Comment by wu-sheng** [comment]
@SataQiu Send the invitation of https://github.com/orgs/SkyAPM/teams/cn-document-team/members

I will be part of this org, but only have privilege of this repo.

**Comment by wu-sheng** [comment]
Committer and PMC team members are default when you are a member of Apache committer/PMC, or your project hosted in this org, such as another language agent.

**Comment by SataQiu** [comment]
@wu-sheng OK, I will try my best. Thank you very much. :smile:

**Comment by kezhenxu94** [comment]
> @wu-sheng OK, I will try my best. Thank you very much. 😄

Congratulations and welcome to join us! Hope we can keep the docs up to date together! Thanks!

**Comment by wu-sheng** [comment]
@SataQiu Just curiosity, are you still at BUAA?

**Comment by SataQiu** [comment]
I graduated with a master's degree in 2017.

**Pull request merged**
